# Generated by Django 3.2.7 on 2021-09-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_article_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalTypeflag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
