# Generated by Django 3.2.7 on 2021-09-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_opticaltypeflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticaltypeflag',
            name='description',
        ),
    ]
