# Generated by Django 3.2.7 on 2021-09-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_opticaltypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeflag'),
        ),
    ]
