# Generated by Django 3.2.7 on 2021-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_opticaltypes_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticaltypes',
            name='types',
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='title',
            field=models.CharField(blank=True, choices=[('1', 'yellow'), ('2', 'red'), ('3', 'black')], max_length=32, null=True),
        ),
    ]
