# Generated by Django 3.2.7 on 2021-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210927_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
