# Generated by Django 3.2.7 on 2021-09-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_opticaltypes_opticaltypeflags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
        migrations.CreateModel(
            name='Kelvin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('post', models.ManyToManyField(to='polls.Post')),
            ],
        ),
    ]
