# Generated by Django 3.2.7 on 2021-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20211002_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='updated',
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
    ]
