# Generated by Django 3.2.7 on 2021-10-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_opticaltypes_opticaltypeflags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
    ]
