# Generated by Django 3.2.7 on 2021-10-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20211004_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='created',
        ),
        migrations.AddField(
            model_name='brand',
            name='Description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
    ]
