# Generated by Django 3.2.7 on 2021-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_alter_opticaltypes_opticaltypeflags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='brand',
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
    ]
