# Generated by Django 3.2.7 on 2021-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_alter_opticaltypes_opticaltypeflags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='material',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='project',
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
    ]
