# Generated by Django 3.2.7 on 2021-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_alter_opticaltypes_opticaltypeflags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='opticaltypes',
            name='opticaltypeflags',
            field=models.ManyToManyField(to='polls.OpticalTypeFlag'),
        ),
    ]
